/* eslint-disable quotes */
// noinspection SpellCheckingInspection
setTimeout(() => {
    let completed = [
        "\"Boatman\"'s Task",
        "A Gift To Shitoki, Wrapped In Conches",
        "Abbas' Escape",
        "Abe's Fungi Needs",
        "Adonis' Abandoned Safehouse",
        "Akashi's Archery Challenge",
        "Buried Chests in Ashavan Realm",
        "Chessboard of Safhe Shatranj",
        "Chouji's Travels",
        "Cryptic Message in Dragonspine",
        "Cryptic Message in Sumeru",
        "Dragonspine's Glacial Secret",
        "Dragonspine's Last Trio",
        "Drusus's Riddles",
        "Eleazar Hospital Notes",
        "Even Beasts Get Homesick",
        "Fatui Action Logs",
        "Find The Chasm Mining Records",
        "For a Rose's Wellbeing",
        "Fourth's a Deathmatch",
        "Gendou Ringo's Strange Fortune Slips",
        "Golden Life, From Yesteryear Awoken",
        "Hanayama Kaoru's Flowery Plan",
        "Ipe's Fishing Advice",
        "Ishine Script Deciphering",
        "Iwakura Art's Downfall",
        "Journey For Tri-Lakshana's Starry Treasure",
        "Khayyam's Final Words",
        "Kito and Kina's Request",
        "Komaki's Spiritherb Fortune",
        "Lighting Chise's Path",
        "Locked Gate in the Nameless Ruins",
        "Lumenspar in the Den of Thieves",
        "Marana's Last Struggle",
        "Memories of Pairidaeza",
        "Muning's Never-Ending Needs",
        "Nonno's Hide And Seek",
        "Opening Old Memories",
        "Oracle Parchment, for the End of Death",
        "Pay Your Respects",
        "Put Them To Rest",
        "Ragged Records",
        "Reading Kabayama's Lanterns",
        "Rero's Joke",
        "Researcher's Notes",
        "Rinzou's Treasure",
        "Searching for Saimon Jirou",
        "Secret Messages in The Chasm",
        "Seed from the Valley of Life",
        "Selling the Dragonbone Orb",
        "Shrines of Yashiori Island",
        "Sunchildren Hide and Seek",
        "Tatarigami Investigation Expedition",
        "The Bad Guy in Vimara Village",
        "The Cat's Affection",
        "The Dead End and the Glinting Architects",
        "The Foxes' Affection",
        "The Murals of Gurabad",
        "The Viparyas of Vanarana",
        "Tsurumi's Mountain Murals",
        "Una's Longing",
        "Washizu's Prayers",
        "Yasumoto's Last Notes",
    ];

    for (const el of document.querySelectorAll('ul > li > a')) {
        if (!completed.includes(el.innerText)) continue;
        el.parentNode.style.backgroundColor = 'darkgreen';
    }
}, 153);
